"""Prompt 模板模块"""

from .report_prompts import (
    REPORT_PLANNING_PROMPT,
    SECTION_WRITING_PROMPT,
    REPORT_REVIEW_PROMPT,
    EXECUTIVE_SUMMARY_PROMPT,
    KEY_INSIGHTS_EXTRACTION_PROMPT,
    CONTENT_CLASSIFICATION_PROMPT,
)

from .business_research_prompts import (
    BUSINESS_RESEARCH_SYSTEM_PROMPT,
    BUSINESS_CLASSIFICATION_PROMPT,
    COMPETITIVE_ANALYSIS_PROMPT,
    GUIDE_GENERATION_PROMPT,
    PRODUCT_ANALYSIS_PROMPT,
)

__all__ = [
    "REPORT_PLANNING_PROMPT",
    "SECTION_WRITING_PROMPT",
    "REPORT_REVIEW_PROMPT",
    "EXECUTIVE_SUMMARY_PROMPT",
    "KEY_INSIGHTS_EXTRACTION_PROMPT",
    "CONTENT_CLASSIFICATION_PROMPT",
    "BUSINESS_RESEARCH_SYSTEM_PROMPT",
    "BUSINESS_CLASSIFICATION_PROMPT",
    "COMPETITIVE_ANALYSIS_PROMPT",
    "GUIDE_GENERATION_PROMPT",
    "PRODUCT_ANALYSIS_PROMPT",
]